### PR TITLE
Contribution: Education: Removing duplicate tutorial page titles - fixes #3554

### LINKED ISSUE #3554: 3. Tutorial Step - Client "Next" Button does not work
Hitting "Next" leads to the same page you are on.. so you can not go to the chapter "4. Tutorial Step - Collection of Servers"

### PR DESCRIPTION
**Pull request by BastianMuc**

### CODE REVIEW

**Comment by gitforkgit** [comment]
@BastianMuc I see you are cleaning up a bit to restore structure. But there are some files where you replace an existing bracket with the same bracket in the same place. Can you give me some context. Did you run a script for this etc. that would help me understand each change.

**Comment by BastianMuc** [comment]
I had the repagination script executed over this tutorial - which at the end was unnecessary, as I ended up changing a page name, but not deleting any of the existing pages (page counts unchanged). I assume the repagination script to trigger the bracket changes.

**Comment by gitforkgit** [comment]
Do you still want this pull request to get merged?

**Comment by BastianMuc** [comment]
Should normally not cause any issues, but to opt on the safe side, I'll close and re-submit.

**Pull request closed without merging**
