### PR TITLE
Contribution: This is my contribution to Superalgos

### PR DESCRIPTION
**Pull request by Aluc4rd91**

### CODE REVIEW

**Comment by julian-molina** [comment]
Not clear what the PR is about. It seems accidental. If not, please clarify and resubmit.

**Comment by Aluc4rd91** [comment]
I don't know anything about it either. Maybe it's related to the fact that
I managed to create my profile at Superalgos yesterday.

Julian Molina ***@***.***> schrieb am Mi., 12. Okt. 2022,
18:27:

**Comment by Aluc4rd91** [comment]
Or not. I think rather this was my previous pull request.

Patrick Wasserberg ***@***.***> schrieb am Mi., 12. Okt.
2022, 18:35:

**Comment by julian-molina** [comment]
Ok... Make sure you are up to date in the develop branch before submitting your profile. That should produce a clean PR.

**Comment by Aluc4rd91** [comment]
I think I paid attention to that before😉

Julian Molina ***@***.***> schrieb am Mi., 12. Okt. 2022,
21:10:

**Pull request closed without merging**
