### PR TITLE
Governance: Support for multiple report files around Bitcoin Factory Rewards

### PR DESCRIPTION
**Pull request by BastianMuc**

### CODE REVIEW

**Comment by gitforkgit** [comment]
@Luis-Fernando-Molina can you have a look at the issue? Deep scan shows problems with code related stuff altough the PR didn`t push any code related stuff.
Maybe something in the backround?

**Comment by BastianMuc** [comment]
@Luis-Fernando-Molina - We now support multiple Testnet result files for rewarding test case executions. Files should be provided into the **./Bitcoin-Factory/Reports/** folder, matching the filename pattern **Testnet*.csv** .

**Comment by gitforkgit** [comment]
@BastianMuc do you know what went wrong with the DeepScan check?

**Comment by BastianMuc** [comment]
> @BastianMuc do you know what went wrong with the DeepScan check?

No clue - the Deepscan comments are totally unrelated to my changes - the sections highlighted by Deepscan weren't touched.

**Comment by gitforkgit** [comment]
@BastianMuc That's how I see it, too. Deepscans comments don't seem to fit this pull request. I would suggest that we close the pull request, you backup the two files and then just push again. Best is to pull the repo before. Maybe that solves the problem if your repo is the same as the main repository?

**Pull request merged**
