### PR TITLE
Contribution: added the Workspace category to the : The docs explained docs

### PR DESCRIPTION
**Pull request by gitforkgit**

### CODE REVIEW

**Comment by harrellbm** [comment]
@gitforkgit This is all good stuff if you need any help solving the merge conflicts let me know so we can get this merged

**Comment by Luis-Fernando-Molina** [comment]
The merge conflicts in this case are because the Telegram Bot and it's docs has been moved to the Social-Bots projects, so those files you translated have been deleted at that location. You need to copy those changes somewhere else, app.update and replace the files at the new project location.

Install Github desktop to verify the differences between the old files and new files so that you are sure that nothing unintended was modified or lost.

**Comment by Luis-Fernando-Molina** [comment]
This Pull Request could not be automatically merged and was closed by the Superalgos Governance System because it was detected that a User Profile file... 

https://github.com/Superalgos/Superalgos/raw/5bbbefc02624900b283e928e4a1383e40e6da093/Projects/Governance/Plugins/User-Profiles/EvaMaria70.json

...was submitted together with  6 other file/s. User Profiles files as per the Governance System rules, must be the only file present at a Pull Request in order to pass all the validations and be automatically merged. 

 If you intentionally submitted the extra files, the way to get your work merged is by first removing your User Profile file from the Plugins folder at your local installation and executing an app.contribute again. Then wait until the PR is merged (manually reviewed) and after that you put your User Profile file again and create a new PR only with that file with an app.contribute. That last PR should be merged automatically.

**Comment by Luis-Fernando-Molina** [comment]
There have not been reported any big bugs so you can work on develop now.

**Comment by gitforkgit** [comment]
So only moving the translated files is enough and later after app.update i only need to put them in the folder they were before?

**Pull request closed without merging**
