### PR TITLE
Added sandbox mode capability

### PR DESCRIPTION
**Pull request by benmarte**
- Added `sandBox: false` as an initial parameter when creating an exchange (file modified: Projects/Superalgos/Schemas/App-Schema/crypto-exchange.json)
- Added `sandBox` documentation entry explaining how to enable/disable sandbox mode (file modified: Projects/Superalgos/Schemas/Docs-Nodes/crypto-exchange.json)
- Added ability to enable/disable sandbox mode (file modified: Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js)

Please review and let me know if any further changes are required.

Thanks.

### CODE REVIEW

**Comment by Luis-Fernando-Molina** [comment]
Hey thanks for this contribution! A lot of people asked to be able to use the test environment before.

**Comment by Luis-Fernando-Molina** [comment]
Can you please resubmit the PR pointing to the develop branch (and based on the develop branch). We are currently merging all changes there so that they can be tested by others before shipping to master. Thanks!

**Comment by benmarte** [comment]
Will do, thanks.

**Comment by benmarte** [comment]
Making PR in develop branch

**Pull request closed without merging**
