### PR TITLE
Create Windows Shortcut Script

### PR DESCRIPTION
**Pull request by harrellbm**
Superalgos-shortcut-windows

Also grouped everything under GUI-Launch folder to keep these launch scripts from cluttering up the main directory.

### CODE REVIEW

**Comment by Luis-Fernando-Molina** [comment]
The folder GUI-Launch is not the best name, since you are launching the Client and the GUI at the same time. Can you please rename it to Launch-Scripts?

**Comment by harrellbm** [comment]
That makes sense. I'll do that right now!

**Comment by Luis-Fernando-Molina** [comment]
Please don't forget to update the docs / readme to help users with these launch scripts.

**Comment by harrellbm** [comment]
You got it. 👌🏼 It's on my tasks list.

**Pull request merged**
