### PR TITLE
Contribution: Education - Translation - Ru - Chapter X - Install a New Market

### PR DESCRIPTION
**Pull request by maxah**

### CODE REVIEW

**Comment by gitforkgit** [comment]
@maxah you accidentally added your user profile and Portfolio management. Those must be in a non documentation pull reqest.

**Review by gitforkgit — CHANGES_REQUESTED** [review]
Please make a seperate pull request for : Plugins/Governance  ,   Plugins/Portfolio-Management.

**Review by maxah — COMMENTED** [review]
image
Where did it come from?

**Comment by gitforkgit** [comment]
@maxah Thats a really good question. I first thought you intended to commit these files but if you didn`t thats a good question. Maybe you were in an different worksapce and accidentally changed something small and then the files were different. If you have a guess that would be great to know for the future.

**Comment by gitforkgit** [comment]
@maxah the files still show up to me, did you try to remove these from the pull request?

**Comment by maxah** [comment]
This happened after 'node setup'.  After the last 'app.update' my UI broke.  And in the 'Support' chat it was advised to clear the browser cache and 'node setup'.  That's all I did except translations.  I only have 2 workspaces: 'Token Distribution' and 'Get in Started' and that's it.

**Comment by maxah** [comment]
I will try to delete these files tomorrow.

**Comment by gitforkgit** [comment]
@maxah that`s good to know if this happens to others. Just tag me if you done the changes :+1:

**Comment by maxah** [comment]
The changes came from 'Submode'. I don't know how to remove them.

**Pull request closed without merging**
