### PR TITLE
Unit tests for startup scripts (minus setupPlugins) and pre-commit hooks

### PR DESCRIPTION
**Pull request by Char1zardd**
-Pre-commit hooks to run unit tests before each commit
-Unit tested 3 other files, and moved the setup files as discussed. Also made 2 setup files, one for regular and one for setup with tensorflow. Removed the old dependency checking as well
-Added linting, but did not include it in pre-commit since linting takes too long. The linter only checks for issues with the code and not style, I think it's unrealistic to enforce a specific style across so many contributors in an open source project. Personally I will be changing 4-space tabs to 2-space tabs, change old functions to arrow functions, etc. wherever i see it and hope people go with this.

### CODE REVIEW

**Comment by Char1zardd** [comment]
Fix for deepscan issues above

**Comment by Char1zardd** [comment]
setupPlugins re-written and ready for unit tests, that will be next

**Comment by Luis-Fernando-Molina** [comment]
hey! I noticed you moved the launch and setup commands inside one folder. Did you update the Readme, potentially docs and tutorials were those scripts might be mentioned to instruct users to look for them inside that folder?

**Comment by Char1zardd** [comment]
Hey man sorry I rarely read this inbox I just use it to sign up to stuff. The overall functionality of the app is the same the only thing that changed is the “meat” of the code is now in launch-scripts for the startup script files

**Pull request merged**
