### PR TITLE
Contribution: This is my contribution to Superalgos

### PR DESCRIPTION
**Pull request by WinterOso**

### CODE REVIEW

**Review by BastianMuc — CHANGES_REQUESTED** [review]
Hey @WinterOso , thanks for your contribution!

It appears as if the commit also included changes to the code you potentially did not want to commit (in launch-windows.bat and package-lock.json).

Please review your commit and ensure to upload only the review.

In case you actually wanted to contribute changes regarding the other files as well, please let us know a bit more about the details. Thank you!

**Comment by WinterOso** [comment]
Hello Bastian, sorry for the inconvenience!

Yes, I did only want to contribute my profile. I uploaded the other two code changes by accident. I will not try to figure out how to change my commit here in order for my profile to be committed correctly.

**Review by WinterOso — COMMENTED** [review]
Only wanted to upload my newly created profile. 
I committed the two other code changes by accident.
Sorry and thanks!

**Comment by BastianMuc** [comment]
Hey @WinterOso , I'm sorry for needing to bother you again!
The way the PR is set now would lead to the files launch-windows.bat and package-lock.json getting deleted for everyone once merged. This probably also isn't what we want to achieve.

It could make sense to close this PR and submit a new one from scratch. The Contributions Tab will give you a preview on which files are recognized as changed, and also allow you to contribute selectively.

Handling git has caused me quite some headaches as well when I started here - don't give up! :-)

**Pull request closed without merging**
