### PR TITLE
Contribution: Fixing PullRequest Indonesian Translation Basic Education page 6 - 13

### PR DESCRIPTION
**Pull request by Mhnramin**

### CODE REVIEW

**Comment by harrellbm** [comment]
@Mhnramin Hey sorry for the confusion we should have the sub repos figured out now. If you update your develop branch again we can get this merged!

**Comment by Mhnramin** [comment]
> @Mhnramin Hey sorry for the confusion we should have the sub repos figured out now. If you update your develop branch again we can get this merged!

App.update and app.contribute ? I will try now

**Comment by harrellbm** [comment]
@Mhnramin Everything looks good except for setup.js getting added to .gitignore.  Once that's fixed I'll merge right away 👍🏼

**Comment by Mhnramin** [comment]
> @Mhnramin Everything looks good except for setup.js getting added to .gitignore.  Once that's fixed I'll merge right away 👍🏼

Has been fixed 👌, you can merge now i think 👍

**Review by harrellbm — APPROVED** [review]

**Pull request merged**
