### PR TITLE
User Profile superharoun

### PR DESCRIPTION
**Pull request by superharoun**
Creation of user profile

### CODE REVIEW

**Comment by superharoun** [comment]
If i got it well, i just sent my user profile

**Comment by superharoun** [comment]
Can someone explain me the failed checks please ?

**Comment by harrellbm** [comment]
It seems that you created your profile on the master branch and are now contributing it to the develop branch I'm guessing that is what the system is complaining about

**Comment by superharoun** [comment]
Makes sense, had a weird message about double remote branches when trying to switch to develop so i tried without switching :).

**Comment by superharoun** [comment]
Will redo once switched to develop branch properly.

**Pull request closed without merging**
