### PR TITLE
Contribution: Education - Translation - Ru - Chapter V - Data Mining - complete

### PR DESCRIPTION
**Pull request by maxah**

### CODE REVIEW

**Comment by harrellbm** [comment]
@maxah Hey we had some issues with the lan-network pages. You should be able to copy the fixed pages from the develop branch and then app.contribute to fix the merge conflicts on this PR

**Comment by maxah** [comment]
Done

**Comment by harrellbm** [comment]
@maxah Im still getting merge conflicts on this PR. GitHub will block merging until we figure them all the way out. Can you see what is getting flagged on your end?

Here is an article walking you through how to solve the conflicts on GitHub 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by maxah** [comment]
Fixed

**Review by harrellbm — APPROVED** [review]

**Pull request merged**
