### PR TITLE
Improve docker info

### PR DESCRIPTION
**Pull request by NITEMAN**

### CODE REVIEW

**Comment by julian-molina** [comment]
Hey @NITEMAN Thank's for the update on the Docker instructions. Unfortunately, we can't merge this directly on the master branch. Can you please resubmit to the plugins-docs branch instead?

**Comment by NITEMAN** [comment]
@julian-molina as far as I can see `plugin-docs` is not up to date with current master (at least it doesn't contains #854 ), so there are conflicts ... I can wait for `plugin-docs` to be rebased/updated to current `master` or resolve commit conflicts against `plugin-docs` probably causing a rebase conflict

**Comment by julian-molina** [comment]
@Luis-Fernando-Molina can you look into this?

**Comment by Luis-Fernando-Molina** [comment]
It's alight, I merged a change in master yesterday and this is part of that.

**Pull request merged**
