### PR TITLE
Update to docs, tuts and UI

### PR DESCRIPTION
**Pull request by jobidon**
Removed many exclamation points from the tutorials
Fixed shortcut generation in linux
and updated the label on the expand button

### CODE REVIEW

**Comment by harrellbm** [comment]
@jobidon Hey for the sake of code review can you split this PR into smaller pieces so that changes can be evaluated by the proper code reviewers?

**Comment by gitforkgit** [comment]
@jobidon is that possible? As it would help delegating the single pull requests to the extra teams.

**Comment by jobidon** [comment]
sure. Should I close this PR and submit each commit as its own PR?

**Comment by gitforkgit** [comment]
@jobidon It would be great if you could make different pull requests for each team. So put all translations in one pull request. Put each "Fixed shortcut generation in linux" into one and "updated the label on the expand button" into one. Remember app.update before you make the new pull requests. That would be great. :+1:

**Pull request closed without merging**
