### PR TITLE
Update DocSchema.json

### PR DESCRIPTION
**Pull request by camaris**
Corrected typo, my first contribution, even my first github contribution, so please correct me if I did it wrong.

### CODE REVIEW

**Comment by camaris** [comment]
Checked it once again. To find the typo, search for "ensystemgine".

**Comment by Luis-Fernando-Molina** [comment]
Hi! Thank you for submitting this pull request. unfortunately I have been working during the last 3 weeks on a new functionality related to the in-app-docs and the current file has been splitted into almost 400 smaller files. That means I can not merge this here, but correct the typo you mentioned in the latest version. I am sorry because this was your first contribution but you will love the new way to update the docs within the app itself, about to be released at the develop branch in a few days. Thanks!

**Comment by camaris** [comment]
Ok, nice, no worries. Good luck ! I'm very new to superalgos but love the
whole idea and setup. Personally I like the UI very much. Two thoughts:
- UI is beautiful, but quite resource intensive. Ever thought of a leaner
version (e.g. more JSON editor oriented) or a basic/enhanced gfx setting
dropping some of the fancy gfx ?
- Complexity is quite overwhelming for a first time user. Any work being
done or ideas on making it less complex ?
Keep up the good work...
Mark

Op vr 25 dec. 2020 12:58 schreef Luis Fernando Molina <
notifications@github.com>:

**Comment by Luis-Fernando-Molina** [comment]
> UI is beautiful, but quite resource intensive. Ever thought of a leaner
version (e.g. more JSON editor oriented) or a basic/enhanced gfx setting
dropping some of the fancy gfx ?

The main reason the UX is resource expensive is because it is a canvas animation running at many frame per seconds. Even if you drop the fancy stuff it would still be resource expensive because it would just do more frames per second. Having said that, there is still a lot of room for improvement if someone spend some time in that topic. 

> Complexity is quite overwhelming for a first time user. Any work being
done or ideas on making it less complex ?

We are working towards doing tutorials at this moment. Complexity is a consequence of flexibility. At this point in time we consider the user to be a developer / tech guy / early adopter. In the future we will build tools so that these first user base can abstract the underlaying complexity and create plug and play bots for a different and wider set of less technical users, that won't probably see the designer, just the interface provided to them with minimum inputs and charts. That is one of the growing dimensions of the project, still only in idea phase.

**Pull request closed without merging**
