### PR TITLE
First update

### PR DESCRIPTION
**Pull request by jobidon**
hopefully it'll work better this time...

### CODE REVIEW

**Comment by harrellbm** [comment]
@jobidon Hey what is the motivation for taking out all the exclamation marks?

You need to be careful changing the titles of articles because that is how the system finds them to display in tutorial, or inclusion in books, etc. 

This looks like a lot of good work! Just want to make sure we don't make a mess if unwanted changes make it through.

**Comment by jobidon** [comment]
... not ALL, but many! :)
It improves readability and allow emphasis to be put on certain points: When used everywhere, the emphasis is lost.

**Comment by jobidon** [comment]
I just realized that perhaps changing the label of the Expand button will break many things... This needs to be investigated further before being pulled to the main repo

**Comment by gitforkgit** [comment]
@jobidon do you want this pull request closed until you know if and how it will break things or open?

**Pull request closed without merging**
