### PR TITLE
Rectify missing configuration file errors in Zeus and Sparta indicators 

### PR DESCRIPTION
**Pull request by Gallymojo**
All indicators in Zeus and Sparta were generating errors - Missing configuration for the Multi-Time-Frame-Market and Multi-Time-Frame-Daily datasets

### CODE REVIEW

**Comment by Luis-Fernando-Molina** [comment]
I made a test of a Sparta indicator and it seems to be running.

**Comment by Luis-Fernando-Molina** [comment]
Zeus seems to be running too.

image

Please send screenshots of the problem before the solution applied.

**Comment by Gallymojo** [comment]
Hi, they do run and the chart loads but every time I
Missing Configuration for Indicators
 looked at the chart with dev tools open I would get a missing config error.

**Comment by Luis-Fernando-Molina** [comment]
ahh ok, I get it now.  Can you please check the other data mines if they have the same problem? I will merge this PR in the meantime.

**Pull request merged**
