### PR TITLE
Contribution: My First Superalgos Review

### PR DESCRIPTION
**Pull request by jobidon**

### CODE REVIEW

**Comment by harrellbm** [comment]
@jobidon @gitforkgit It looks like we got a ton of other files mixed with this review. Do you know how to run a fetch and merge on your develop branch?

**Comment by jobidon** [comment]
@harrellbm as you correctly alluded to, I am still learning how to work with git. When I submitted my review of SA, it looks like it also bundled all other changes I had tentatively flagged, including a plethora of exclamation points that I tried to mitigate a bit. Nonetheless, let me know what I need to do to make this easier for you.
Thanks for your patience in walking me through this :)

**Comment by gitforkgit** [comment]
Hey @jobidon to fix this problem, click on your profile picture in the top right corner . Now a drop down menu should show Up. Then click on: "Your profile". After that you should see an Overview of your profile. Now click on Superalgos (under Superalgos there should stand: "Forked from Superalgos/Superalgos"). Now click on master if there doesn`t stand something else. Again a drop down menu should show up. Now choose: "develop". Now go to the right and click on: Fetch upstream. A small menu should pop up where you can click: "fetch and merge" . Click on: "fetch and merge" and the problem should be resolved.
Let me know if you got questions :+1:

**Comment by jobidon** [comment]
done, thanks for the detailed walkthrough!

**Comment by gitforkgit** [comment]
@jobidon As the other files still show up, you could maybe delete all files but the review file, so we can merge your pull request. If you wanted to add all the other files, please let me know. @harrellbm what do you think?

**Comment by gitforkgit** [comment]
@jobidon could you please tell if this changes at the most files not being the review where intended or happened accidentally.
:+1:

**Comment by jobidon** [comment]
Yes, these files all contain modifications.

**Comment by Luis-Fernando-Molina** [comment]
Please copy your review file elswhere, refork and resubmit.

**Pull request closed without merging**
