### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by end-debug**

### CODE REVIEW

**Comment by ssplatt** [comment]
why is the package-lock.json being updated? is there something specific you are trying to accomplish?

**Comment by Luis-Fernando-Molina** [comment]
@end-debug please remove the package json from your commit. @ssplatt shouldn't package json be git ignored?

**Comment by ssplatt** [comment]
it is in the git ignore but i'm not entirely sure why that is not respected. It shouldn't be ignored, really, and we should fix whatever automated command (app.update?) that keeps updating it and including it in the PRs.

**Comment by end-debug** [comment]
This usually happens when I do a npm update and some dependencies get
updated plus I don't know how to remove commits.

still Github desktop and stashing somethings before committing

**Comment by Luis-Fernando-Molina** [comment]
get the latest package-lock.json from the repository develop branch into your local repository and do an app.contribute again. That will fix it.

**Pull request closed without merging**
