### PR TITLE
Contribution: (translation into german: "App contribute command")

### PR DESCRIPTION
**Pull request by gitforkgit**

### CODE REVIEW

**Review by harrellbm — COMMENTED** [review]
Make sure this icon changes is correct otherwise this looks great!

**Comment by Luis-Fernando-Molina** [comment]
@harrellbm I noticed those Icon changes at other PRs, it looks like they are involuntary and unrelated to the translating work being done. You should find the root cause of them, looks like a bug.

**Comment by Luis-Fernando-Molina** [comment]
At a previous PR I manually fixed them, but now I am not sure if the system is not auto correcting an icon definition that is wrong, or is corrupting something that is right. Before more manual stuff someone should check that out.

**Comment by Luis-Fernando-Molina** [comment]
Shall we merge this?

**Review by harrellbm — CHANGES_REQUESTED** [review]
Are you submitting things from a new getting started workspace? I haven't been able to track down why icons are getting changed like this on accident still

**Comment by gitforkgit** [comment]
You mean i should app.update since i wasnt working on superalgos for the last couple of days?
Shall i update and then resubmit?

**Review by harrellbm — APPROVED** [review]

**Comment by harrellbm** [comment]
Perfect that cleared it up!

**Pull request merged**
