### PR TITLE
Contribution: This is my contribution to Superalgos

### PR DESCRIPTION
**Pull request by maxah**

### CODE REVIEW

**Review by harrellbm — COMMENTED** [review]
Hey just had a quick questions before I approve this.  What feature are you working on with the project.properties and project.xml files?

**Comment by maxah** [comment]
> 

I am engaged in the translation of documentation into Russian. I didn’t seem to touch the project.properties and project.xml files.

**Review by harrellbm — CHANGES_REQUESTED** [review]
Everything looks great except for the bots in Superalgos page. It looks like a few paragraphs are getting deleted by accident.  Once that is fixed I'll make sure this gets approved!

**Comment by maxah** [comment]
Guys, should I keep working?

**Comment by Luis-Fernando-Molina** [comment]
Waiting for @harrellbm , you might continue translating but don't send more changes to this PR until merged. The more files, the more difficult to review.

**Review by harrellbm — APPROVED** [review]

**Pull request merged**
